import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const chronicaPro = localFont({
  src: [
    {
      path: "../public/fonts/ChronicaPro-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-chronica",
  display: "swap",
  fallback: ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/logoPrisma360.png",
        width: 512,
        height: 512,
        alt: "Prisma360 Consultora logo",
      },
    ],
  },
  icons: {
    icon: "/logoPrisma360.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chronicaPro.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
